### ISSUE TITLE
Visualizar detalhes de um documento submetido

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-upload#10]
### Descrição da nova funcionalidade
Como **depositante**, ao acessar os detalhes de um documento, eu gostaria de **poder visualizar um cabeçalho e todas as opções para atuar sobre o documento**, assim **poderei administrar melhor os documentos submetidos por mim**.

### Critérios de aceitação
1. Cabeçalho com dados do pacote: nome do pacote zip, data de upload, data do último evento, componentes do pacote
2.  ~Cabeçalho com dados do documento, se aplicável: título, seção do sumário, ano, (identificação do fascículo), lista de autores, doi, data de publicação.~
3. Apresentar links / botões para:
- [ ] visualizar relatório de formação de XML e/ou DTD
- [ ] visualizar relatório de estilo
- [ ] visualizar relatório de validação de conteúdo individual
- [ ] visualizar relatório de validação de conteúdo no contexto do conjunto (fascículo / journal)
- [ ] visualizar relatório dos ativos digitais
- [ ] previsualização do HTML
- [ ] visualizar XML
- [ ] concluir depósito (se aplicável, se o documento está sendo verificado pelo depositante e este está satisfeito)
- [ ] visualizar parecer do QA (se existir)
- [ ] link para o artigo publicado (se já estiver publicado)

Notas: 
- A página dos respectivos links não precisam estar respondendo
- Um botão `Detalhes` deve ser adicionado para visualizar os detalhes do pacote/documento na tela que lista pacotes
- Uma página nova deverá ser aberta apresentando os dados exigidos neste PR

**Comment by rafaelpezzuto** [comment]
@robertatakenaka @gitnnolabs,

Um view padrão do Wagtail é a InspectView, que me parece ser bastante adequada para a finalidade deste PR. Vou seguir analisando como customizá-la para conter todas as infos que o PR exige.

**Referências**
https://docs.wagtail.org/en/stable/reference/contrib/modeladmin/inspectview.html

**Tela que mostra o que é uma InspectView padrão**
![image](https://user-images.githubusercontent.com/2096125/182398717-22c52172-38a3-43ee-8069-220730ea0fe5.png)

**Comment by robertatakenaka** [comment]
@rafaelpezzuto vamos usar o design system. Vou abrir novo issue só para isso. Por ora, só apresente as info

**Comment by rafaelpezzuto** [comment]
@robertatakenaka Quando disse "customizar", me referi a fazer com a que essa mesma tela apresenta as outras informações:
- componentes do pacote
- links/botões para aquelas ações

A opção é usar a InspectView e alterá-la de modo a exibir tudo isso ou criar uma view nova.

@robertatakenaka Reforçando, não se trata de estilização (design system).
