### ISSUE TITLE
Rejeitar de pacotes com ausência de ativos digitais e renditions

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-upload#18]
### Descrição da nova funcionalidade
Como **analista de qualidade**, eu quero que **o sistema rejeite automaticamente documentos com ausência de ativos digitais**, assim **garantimos que ingresse apenas pacotes válidos**.

### Critérios de aceitação
- Execute a otimização do pacote (packtools)
- A validação é em cima do pacote otimizado
- Apresente em uma página para cada `*graphic*`, com os correspondentes `@id` ou algo que identifique o item, as versões: miniatura, padrão e original e as respectivas imagens.
- Destaque os itens ausentes
- Verifique também os _renditions_. Avaliar se o nome do arquivo contém o idioma correspondente. Apresente os renditions encontrados.
- Registre o resultado na base de dados
- Rejeite se não houve correspondência entre menção no XML e presença do arquivo no pacote

**Comment by rafaelpezzuto** [comment]
@robertatakenaka não estou neste issue ainda (finalizando 18), porém, seria bom adiantar alguns esclarecimentos, se puder:
1. Poderia indicar qual é a otimização a que se refere? (só indicar a função chamada já ajudaria, por exemplo, `packtools.optmize`)
2. Vamos usar aquela modelagem SPS_Package (que tem classes do tipo assets, etc)?
3. Registrar resultados em base de dados seria aumentar um pouco aquele ValidationError para comportar mais campos específicos dessa etapa. Talvez basta criar um campo novo no ValidationError, tal como "annotation". Você pensa algo diferente disto?

**Comment by robertatakenaka** [comment]
> 1. Poderia indicar qual é a otimização a que se refere? (só indicar a função chamada já ajudaria, por exemplo, `packtools.optmize`)

https://github.com/scieloorg/opac-airflow/blob/a2ee0b507dfeb2f83f9eee72dead2ae5f05c8e09/airflow/dags/operations/sync_documents_to_kernel_operations.py#L133



> 2\. Vamos usar aquela modelagem SPS_Package (que tem classes do tipo assets, etc)?

Não, por favor, porque está fazendo coisas demais. Prefiro que você crie uma nova classe cujo foco é obter os `assets`. Por exemplo, quando tive que manipular os dados de autores, criei um módulo e no módulo uma classe correspondente e, dependendo do caso, pode haver mais classes no mesmo módulo. https://github.com/scieloorg/packtools/tree/master/packtools/sps/models
E recomendo que o parâmetro para criar a classe se já um xmltree.
Veja como uso as classes criadas nesta pasta:
https://github.com/robertatakenaka/scielo_core/blob/2730aa9f09648fdb9520bc7dab07f641c14ebd74/scielo_core/id_provider/xml_sps.py#L8
https://github.com/robertatakenaka/scielo_core/blob/2730aa9f09648fdb9520bc7dab07f641c14ebd74/scielo_core/id_provider/xml_sps.py#L100
https://github.com/robertatakenaka/scielo_core/blob/2730aa9f09648fdb9520bc7dab07f641c14ebd74/scielo_core/id_provider/xml_sps.py#L118



> 3\. Registrar resultados em base de dados seria aumentar um pouco aquele ValidationError para comportar mais campos específicos dessa etapa. Talvez basta criar um campo novo no ValidationError, tal como "annotation". Você pensa algo diferente disto?
Sim, tem que ter o annotation. A estrutura tem que ser similar a que existe no XC. (desculpe não tinha percebido que estava faltando)
A tabela vai ser a mesma. Acho que não precisa de mais campos. Exemplo de mensagem:
Arquivo `arquivo.jpg` **está** mencionado no XML mas **não está** presente no pacote.
Arquivo `arquivo.jpg` **não está** mencionado no XML mas **está** presente no pacote.
....

<img width="1178" alt="Captura de Tela 2022-08-05 às 14 58 26" src="https://user-images.githubusercontent.com/505143/183134243-63a90322-e188-465f-952a-ed994991dcda.png">
<img width="1259" alt="Captura de Tela 2022-08-05 às 14 59 02" src="https://user-images.githubusercontent.com/505143/183134255-2a6d5529-26cf-447e-8ad7-4c79fc9baa02.png">
