### ISSUE TITLE
Disparar tasks de validação para pacote carregado

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-upload#19]
### Descrição da nova funcionalidade

Como **analista de qualidade**, eu quero que o **sistema automaticamente faça com que os pacotes passem pelas validações**, assim **tira a necessidade de fazê-lo manualmente**.

### Critérios de aceitação
Tasks:

- Dispara a tarefa desenvolvida em (#17)

Se bem formado:
Tasks:
- Avaliação da estrutura do XML que gera o Relatório da Estrutura (issue a ser criado)
- Otimização dos ativos digitais > Geração do relatório de ausência de ativos digitais e/ou renditions (#18)
- Geração do HTML (#11)

Quando todas terminem deve haver uma mudança de estado do pacote para `VALIDATED_WITH_ERRORS` ou `QA` (sem erros)

### Notas
- Algo relacionado à https://docs.wagtail.org/en/stable/editor_manual/administrator_tasks/managing_workflows.html?highlight=workflow pode ser útil

**Comment by rafaelpezzuto** [comment]
@robertatakenaka Acredito que esta issue é repetitiva, pois o procedimento que faz o disparo automático das tasks é adicionado na issue #18 (vide PR atual).

**Comment by rafaelpezzuto** [comment]
@robertatakenaka 

Há algumas libs legais que lidam com workflow: https://djangopackages.org/grids/g/workflow/?python3=1&stable=1.

Mas a tarefa pode ser resolvida simplesmente com uma tela/endpoint que apresenta botões para disparar tasks celery.

Também tem o flower já embutido na aplicação scms-upload (que seria um monitor e gerente do celery).

Há bons pacotes que lidam com workflow/máquina de estados: [django packages - workflow](https://djangopackages.org/grids/g/workflow/?python3=1&stable=1). A viewflow parece ser bastante poderosa (mas é exagerada para tarefa, do meu ponto de vista atual).

Eu fiz alguma pesquisa, mas acho que os detalhes indicados são insuficientes para avançar com esta tarefa.

**Comment by robertatakenaka** [comment]
@rafaelpezzuto o código como está hoje atende já este issue que pode ser fechado
