### ISSUE TITLE
Incorporar os PR de dependências e testar

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-upload#196]
### Descrição da tarefa
- https://github.com/scieloorg/scms-upload/pulls/app%2Fdependabot
- https://github.com/scieloorg/scms-upload/pulls?q=is%3Aopen+is%3Apr+snyk

**Comment by rg3915** [comment]
Foram aprovados os seguintes PRS:

* https://github.com/scieloorg/scms-upload/pull/156
* https://github.com/scieloorg/scms-upload/pull/164
* https://github.com/scieloorg/scms-upload/pull/166
* https://github.com/scieloorg/scms-upload/pull/172
* https://github.com/scieloorg/scms-upload/pull/173
* https://github.com/scieloorg/scms-upload/pull/176
* https://github.com/scieloorg/scms-upload/pull/179
* https://github.com/scieloorg/scms-upload/pull/184
* https://github.com/scieloorg/scms-upload/pull/185
* https://github.com/scieloorg/scms-upload/pull/188
* https://github.com/scieloorg/scms-upload/pull/191
* https://github.com/scieloorg/scms-upload/pull/192
* https://github.com/scieloorg/scms-upload/pull/193
