### ISSUE TITLE
Concluir o depósito com justificativa

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-upload#33]
### Descrição da nova funcionalidade
Eu como **depositante**, quero **ser capaz de justificar os motivos de não corrigir os erros informados pelos relatórios**, assim **o meu depósito será analisado e validado** para uma posterior publicação em uma coleção SciELO

### Critérios de aceitação
A partir da página de detalhes do pacote (#10), terei um link para uma página em que listará todos os erros encontrados (que não rejeitem automaticamente o pacote).
Para cada um destes erros, posso indicar uma das opções: `farei a correção`, `discordo`, `não sei como resolver` e, um campo opcional para justificativa ou comentário.
O usuário pode parar a qualquer momento, então as opções e comentários devem ser guardados em tempo real, ou evitar que o trabalho seja perdido.
Quando o usuário completar, o sistema deve avaliar se há algum item `farei a correção`, então, o status do pacote é `pendente de correção`. 
Havendo erros com a declaração de `discordo` ou `não sei como resolver`, o usuário pode "concluir o depósito" e aguardar o parecer ou o apoio da equipe de QA, então o status do pacote passa para `QA`.

**Comment by rafaelpezzuto** [comment]
### Minhas notas
- Criar link em página de detalhes que abre uma página contendo todos os erros relacionados ao pacote
    - A página `detalhes` já existe - acho que basta fazer com que ela enxergue as validações ocorridas
- Na página aberta, para cada erro, permitir o usuário a determinar uma ação a ser feita, dentre `farei a correção`, `discordo`, `não sei como resolver`.
    - É preciso criar um novo modelo `Ação` que deve estar relacionada a cada `ValidationError`
    - ValidationError 1 -- 1 Action
- Incluir um campo opcional `comentário` nessa determinação de ação
    - Esse novo modelo deve ter campo `annotation` para guardar comentário
- A página que determina essa ação e inclui ou comentário deve ser salva em tempo real
- Caso alguma ação seja do tipo `farei correção`, o sistema deve alterar o estado do pacote para `pendente de correção`
    - O campo status muda para um novo estado (`PENDING_CORRECTION`) 
- Havendo erros do tipo `discordo` ou `não sei como resolver` o usuário pode concluir o depósito
    - O campo `concluir depósito` ficaria ativo
    - Quando acionado o estado do pacote passa para `QA` (**dúvida - o estado `Accepted` não existiria?**)
- A próxima fase seria uma análise de um QA para dar um parecer.
