### ISSUE TITLE
Listar os pacotes com status "QA" para os usuários QA

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-upload#35]
### Descrição da nova funcionalidade
Como **analista de qualidade**, dada uma lista de pacotes, eu quero **ser capaz de visualizar na lista de pacotes em "QA" a quantidade ~e porcentagem~ de erros de cada classificação: (a) não sei resolver e (b) não concordo**, assim **posso decidir a que pacotes dar prioridade**.

### Critérios de aceitação
~Na lista de pacotes gostaria de ordenar por quantidade de erros que o usuário recusou corrigir (pode ser um falso positivo).~
~Na lista de pacotes gostaria de ordenar por quantidade de pedidos de ajuda.~

O importante desta visualização é o QA identificar mais prontamente os depositantes que não sabem resolver os erros.
Sendo assim, algo pesquisável no registro que o QA localize rapidamente depositantes que precisam de ajuda.

**Comment by rafaelpezzuto** [comment]
### Minhas notas
- É uma página nova cujos campos seriam calculados em tempo de visualização?
    - Qtde de erros por categoria
    - Percentual de erros por categoria
    - Ação a ser tomada
- Ou é um modelo novo que concentra esses campos e são povoados a cada vez que algo novo surge?

**Comment by rafaelpezzuto** [comment]
@robertatakenaka Acredito que o atual PR já resolve isso que está descrito.

Você acha que alguma modificação é necessária?
