### ISSUE TITLE
Visualizar o parecer do QA

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-upload#36]
### Descrição da nova funcionalidade
Como **depositante**, eu gostaria de **ser capaz de visualizar o parecer do QA**, assim **eu saberei porque o pacote foi rejeitado**.

### Critérios de aceitação
A partir da página de detalhes do pacote (#10), terei um link para uma página em que listará todos as solicitações e orientações de correção feitas pela análise de qualidade para mim, o depositante, junto a cada item de erro.

**Comment by rafaelpezzuto** [comment]
@robertatakenaka,

A ideia é sobrescrever os campos já existentes (error_resolution.action e error_resolution.comment) ou criar novos? Sobrescrevendo, obviamente, perdemos a capacidade de contar opinião (qa) e ação (dep) que não coincidem. Mas acho que podemos usar aquele sistema de log que vc sugeriu para manter um tracking das mudanças dos campos (mas acho que isso de tracking seria outro PR - ou não?).

Veja que o modelo ValidationError contém:

- id (id do erro)
- package_id (chave estrangeira)
- error_resolution.comment (dep)
- error_resolution.action (dep)
- error_resolution_opinion.comment (qa)
- error_resolution_opinion.opinion (qa)

**Comment by rafaelpezzuto** [comment]
Segue tela que apresenta botão para acesso a relatório de QA
![image](https://user-images.githubusercontent.com/2096125/187481018-2e0b9b89-70ea-4a93-81ff-dc151710ad23.png)

**Comment by rafaelpezzuto** [comment]
Segue tela que apresenta relatório de QA:
![image](https://user-images.githubusercontent.com/2096125/187481148-32d96386-e9fb-4d11-b377-80735f4945ef.png)
