### ISSUE TITLE
Solicitar mudança

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-upload#49]
### Descrição da nova funcionalidade
Como **analista de qualidade**, eu quero **ser capaz de solicitar mudança** por identificar algum erro / inconsistência para que **o conteúdo seja corrigido**.

### Critérios de aceitação

O usuário QA deve fazer uma busca no sistema pelo documento, e clicar em um botão "Solicitar mudança".
Ou clicar em "Solicitar mudança" e informar o PID do documento no formulário.
O sistema disponibiliza um formulário para o QA fazer a solicitação.
O usuário QA deve:
- selecionar quem fará a correção: um usuário individual.  _Futuramente poderá selecionar um usuário individual e / ou uma equipe (SciELO, do periódico ou produtora de XML)_
-  informar em um campo texto os itens a serem corrigidos (Rich, que permita link, imagem, etc)
- informar um prazo para a mudança
- indicar se é caso de errata ou correção

O sistema deve:
- gravar um status como REQUIRED_ERRATUM ou REQUIRED_UPDATE
- gerar um pacote e um link para descarga do pacote ao gravar a requisição
- gravar o ID do documento
- gravar o usuário solicitante
- gravar o usuário depositante selecionado
- data da solicitação
- texto da solicitação
- tipo de mudança (errata ou correção)
- prazo

**Comment by rafaelpezzuto** [comment]
@robertatakenaka:
Olhei esta e as outras issues deste milestone.

Avaliando a milestone, entendo que é preciso o QA ser capaz de pesquisar por PID ou algum identificador, para dar início ao "solicitar mudança". Também entendo que de alguma maneira, um pacote deve ter um PID ou outro identificador associado (v2, v3, etc...). Talvez seja hora de completar aquela issue inicial da primeira milestone (adicionando no pacote os campos PIDv2, PIDv3 e colection). 

Veja que no modelo atual `Package` não temos PID ou qualquer outro identificador que não seja aleatório.

1. Você acha que PID ou DOI ou algo similar seria um campo "char" do Pacote ou uma chave estrangeira do Pacote (ou nenhum dos dois)?
2. Na situação de ser chave estrangeira, você acha que devemos criar uma app básica `Document` com os itens mais elementares de um artigo (PID v2, PID v3, etc)? Assim a chave de um `Document` seria vinculada a um pacote (via chave estrangeira) durante o depósito/validação.

Faço essas perguntas porque esta issue diz `O usuário QA deve fazer uma busca no sistema pelo documento, e clicar em um botão "Solicitar mudança".

**Comment by robertatakenaka** [comment]
> Avaliando a milestone, entendo que é preciso o QA ser capaz de pesquisar por PID ou algum identificador, para dar início ao "solicitar mudança".
Sim

**Comment by rafaelpezzuto** [comment]
@robertatakenaka 
Acredito que a própria tela que lista os pacotes (estando logado como QA) pode ser adequada para ter o botão "Solicitar mudanças". Esse botão também pode aparecer na tela de inspeção do pacote, facilmente.

A pergunta que tenho é: em que situação (status) uma solicitação de mudança deve ser feita? (`pending-correction`, etc...)

Veja:

![image](https://user-images.githubusercontent.com/2096125/188503013-e7f0b007-f885-4710-a161-f43210d0b5bb.png)

![image](https://user-images.githubusercontent.com/2096125/188503048-85520597-49d3-4d83-8a0f-ed4aa5d44e92.png)
