### ISSUE TITLE
Depositar um pacote corrigido com ERRATA

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-upload#51]
### Descrição da nova funcionalidade
Como depositante, eu quero ser capaz de depositar um pacote corrigido com ERRATA para que seja atualizado no acervo de um periódico da coleção SciELO.

### Critérios de aceitação
O sistema deve aceitar que o pacote há 2 documentos, cujo conteúdo deverá ser avaliado em conjunto, um é o documento modificado contendo uma nota de alteração e o outro é o documento do tipo errata.
As validações que devem ser feitas no momento de ingresso são:
- O pacote recebido já está associado com um registro no sistema de solicitação de errata. (#49)
- No pacote há 2 documentos
- No XML de errata deve haver:
   - `article/@article-type='correction'` a tag `related-article`
   - `related-article` [2][3]
- No XML do documento corrigido deve haver:
   - `fn` contendo a nota sobre a errata [2]
   - Comparar os arquivos para evitar atualização indevida (atualização de documentos diferentes)

Para manter consistência o usuário deve enviar o pacote completo, mesmo sem alteração nos ativos digitais (no entanto, certamente haverá alteração no pdf)

### Referências
[1] https://wp.scielo.org/wp-content/uploads/guia_errata.pdf
[2] https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/narr/errata.html
[3] https://www.scielo.br/j/jbchs/a/Z6mnK3PjKhDZtHJQJYPzxpw/?lang=en&format=xml
[4] https://www.scielo.br/j/jbchs/a/GhMM3hnzCGYBnJhhbYrFfHw/?lang=en&format=xml

**Comment by rafaelpezzuto** [comment]
@robertatakenaka Em relação ao seguinte trecho
```
No XML do documento corrigido deve haver:

    fn contendo a nota sobre a errata [2]
```
Ao observar o artigo corrigido, encontro:
![image](https://user-images.githubusercontent.com/2096125/190682085-f596ee3a-0d4a-4b60-aedb-857a9a1a529d.png)

E no XML há o seguinte:
![image](https://user-images.githubusercontent.com/2096125/190682382-ebf7514c-d511-43bb-8615-515d373f9b9a.png)

Observe que não há um elemento `fn` circundando os parágrafos da correção. Isso é esperado? (o exemplo está no link que você sugeriu na Issue). 

Pensando em packtools.sps.models, há o `related_articles` e já vi que funciona para a errata. Porém, para o XML corrigido, como obter o elemento Errata sem recorrer ao texto interno das tags?

**Comment by rafaelpezzuto** [comment]
@robertatakenaka Analisando todos os quatro artigos corrigidos pela errata indicada na issue, apenas um deles está envolvido por tags `fn` (https://www.scielo.br/j/jbchs/a/zTn4sYXBrfSTMNVPF5Dm7jr?format=xml). Veja:
![image](https://user-images.githubusercontent.com/2096125/190686320-c382129c-a0f8-45ef-a97b-a3c9abaed99d.png)

Observei também que nos outros três casos a indicação da errata está em `<body>`. E no caso desta mensagem, a indicação está dentro de `<back>`.

Mas ok, vou prosseguir a história considerando o que é canônico (conforme documentação que você indicou em https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/narr/errata.html):
```
...
<back>
    ...
    <fn-group>
      <fn fn-type="other">
        <label>Errata</label>
          <p>Texto da errata</p>
          <p>Texto da errata</p>
        </fn>
    </fn-group>
    ...
</back>
...

**Comment by rafaelpezzuto** [comment]
@robertatakenaka observe tbm que estando em `back`e no formato esperado, o site renderiza diferente (acho que neste caso, corretamente):

![image](https://user-images.githubusercontent.com/2096125/190686680-148d5f1b-d0da-4b15-9263-9dd34001d914.png)
