### ISSUE TITLE
Visualizar a lista de pacotes submetidos por mim (depositante)

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-upload#9]
### Descrição da nova funcionalidade
Visualizar a lista de pacotes depositados por mim
Como **depositante**, eu quero **ser capaz de visualizar a lista de todos os pacotes depositados por mim, filtrados por status, ~e com apresentação de título, autores, periódico, ano, volume, número~**, assim **poderei administrar e acompanhar o progresso de cada submissão**.

### Critérios de aceitação
1. A lista deve conter as colunas:
- data do upload
- ~dados do artigo: título, autores~
- ~dados do fascículo/periódico: periódico, ano, vol (num [suppl])~
- status
- data do último evento
- nome do arquivo

2. Lista deve ser filtrada por status ~, dados do periódico~
3. Lista deve ser ordenada por data do último evento e data de upload
4. Lista deve ser pesquisável por ~título, autores,~ nome do arquivo

ADDED
5. A lista deve conter apenas os itens submetidos pelo usuário

### Anexos
n/a

### Referências
n/a

**Comment by rafaelpezzuto** [comment]
@robertatakenaka,

Vou iniciar duas discussões:

1. Quanto aos dados em si:
É interessante mesmo o usuário saber os campos que você sugeriu, porém, nem sempre todos estarão preenchidos (um ahead, por exemplo, estará sem volume). O que pode ser bom, pois, bastaria um pequeno passo para migrar um ahead para um volume.
Veja que ao ser criado, o pacote não terá esses campos preenchidos (apenas os mais básicos). Esses outros campos seriam uma task celery que abre o pacote e os preenche. Então, aí já teríamos um outro estado ("processando pacote"). Gosto dessa abordagem. A assinatura de um pacote tbm seria criada via task celery.

2. Quanto aos modelos:
Você acha que o próprio modelo `Package` deve ter os campos "título do artigo", "autores", título do periódico, ISSN do periódico, ano, volume e número por meio do contéudo do XML? Uma coisa é o que tem dentro do pacote, outra é o que tem na app "journals" e no opac (article).

**Comment by robertatakenaka** [comment]
> 1. É interessante mesmo o usuário saber os campos que você sugeriu, porém, nem sempre todos estarão preenchidos (um ahead, por exemplo, estará sem volume). O que pode ser bom, pois, bastaria um pequeno passo para migrar um ahead para um volume.

claro, o que quis dizer é um "identificador do fascículo / journal" para humanos

**Comment by robertatakenaka** [comment]
> 1. Veja que ao ser criado, o pacote não terá esses campos preenchidos (apenas os mais básicos). Esses outros campos seriam uma task celery que abre o pacote e os preenche. Então, aí já teríamos um outro estado ("processando pacote"). Gosto dessa abordagem. A assinatura de um pacote tbm seria criada via task celery.

Fato! Preencher conforme está disponível. Mesmo porque de um XML mal formado não há como obter os dados

**Comment by robertatakenaka** [comment]
> 2\. Você acha que o próprio modelo `Package` deve ter os campos "título do artigo", "autores", título do periódico, ISSN do periódico, ano, volume e número por meio do contéudo do XML? Uma coisa é o que tem dentro do pacote, outra é o que tem na app "journals" e no opac (article).

Não deve ter. `Package` é nível pacote, suponho. Mas `"Package.document"` pode ter os dados do documento.

**Comment by robertatakenaka** [comment]
@rafaelpezzuto vou simplificar esta estória e deixar a original para o futuro

**Comment by rafaelpezzuto** [comment]
@robertatakenaka Por que? A história já está bem, a questão é que nível de detalhe queremos. Por exemplo, ter um package.document pode ser feito de várias maneiras. A questão é se queremos ter um modelo "Document" definido na aplicação scms-upload, ou se devemos criar uma nova app "document" ou se devemos importar o modelo do opac.article. O mesmo vale para "journal" e para "issue", por exemplo.

Acho que aqui é o caso de termos modelos locais na app upload mesmo.

**Comment by robertatakenaka** [comment]
@rafaelpezzuto é que  pensando bem se o xml estiver mal formado não tem de onde obter estes dados mesmo... então vamos simplicar agora e depois se necessário acrescentamos outras colunas

**Comment by rafaelpezzuto** [comment]
@robertatakenaka entendido.

**Comment by rafaelpezzuto** [comment]
@robertatakenaka No momento, temos os seguintes estados e papéis:

```python
from django.utils.translation import gettext as _


PACKAGE_STATE = (
    (1, _('Submitted')),
    (2, _('Accepted')),
    (3, _('Enqueued for validation')),
    (4, _('Validated without errors')),
    (5, _('Validated with errors')),
    (6, _('Rejected')),
    (7, _('Scheduled for publication')),
    (8, _('Published')),
)

ASSIGNMENT_ROLE = (
    (1, _('Depositor')),
    (2, _('Quality analyst')),
)
```

**Comment by rafaelpezzuto** [comment]
@robertatakenaka 

Precisei avançar um pouco na questão de permissões e cheguei num código interessante. Nós teremos dois grupos, por enquanto, QA e Depositante. Adicionei permissões personalizadas via código, conforme a seguinte lista:

```python
permissions = (
    ("accept", _("Can accept")),
    "enqueue_for_validation", _("Can enqueue for validation")),
    ("reject", _("Can reject")),
    ("preview", _("Can preview")),
    ("schedule_for_publication", _("Can schedule for publication")),
)
```

Usuário depositante veria +ou- isso **dependendo do estado do pacote**:
![image](https://user-images.githubusercontent.com/2096125/181391938-609e05cc-85e1-4d2f-912b-22e5b7b98987.png)

Usuário QA veria +ou- isso se o estado do pacote for **"submetido"**:
![image](https://user-images.githubusercontent.com/2096125/181392085-419b9457-540d-43f4-8b7d-c07b50fa7e69.png)

Usuário QA veria isso se o estado for **"validado"**
![image](https://user-images.githubusercontent.com/2096125/181392353-fd1b0232-5143-43e0-acdb-4d96ae768067.png)

Estou fazendo mais alguns passos e ainda nesta semana (quem sabe quinta) submeto o PR.

**Comment by robertatakenaka** [comment]
Falta parêntesis no início
> "enqueue_for_validation", _("Can enqueue for validation")),

**Comment by robertatakenaka** [comment]
@rafaelpezzuto não acrescentei na lista as ações que os usuários pode fazer porque não acho que não depende somente do status, mas em alguns casos das validações. A única ação necessária no momento é ver detalhes.

**Depositante** em nenhum momento aceita nem rejeita em nenhum estado. O estado `submetido` é para uso do sistema. Com este status, o sistema dispara as validações. Não acho que nenhum usuário dispararia as validações.

**QA** não veria os documentos **submetidos**, mas sim os **depositados**, ou seja, aqueles que o depositante verificou os relatórios de validação e aceito que o pacote está bom o suficiente para ir para QA. Então, o QA só veria:

```
    (2, _('Accepted')),
    (4, _('Validated without errors')),
    (5, _('Validated with errors')),
    (6, _('Rejected')),
    (7, _('Scheduled for publication')),
    (8, _('Published')),
```
Note que a estória é somente sobre o **depositante** e, não sobre o **analista de qualidade**. O detalhe é que o **depositante** só deve ver aquilo que ele submeteu. Já o **analista de qualidade** deve ver todos os documentos depositados. Ou seja, lembrar de levar em consideração o quanto o depositante vê.

**Comment by rafaelpezzuto** [comment]
@robertatakenaka esta `issue` deve ser encerrada?
